/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import config.Session;
import config.conf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER30
 */
public class CreateTransac extends javax.swing.JFrame {

    /**
     * Creates new form CreateTransac
     */
    public CreateTransac() {
         if (Session.getInstance().getU_id() == 0) {
        JOptionPane.showMessageDialog(null, "Please login first!");
        laroa.login log = new laroa.login();
        log.setVisible(true);
        this.dispose();
        return;
     }
     
    initComponents();
    loadProductsTable();  // <-- THIS (not loadTransactionsTable)
}
     private void loadProductsTable() {
    DefaultTableModel model = (DefaultTableModel) transactiontbl.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{"Product ID", "Product Name", "Description", "Price", "Stock", "Category", "Status"});

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conf dbConfig = new conf();
            conn = dbConfig.connectDB();
            
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Database connection failed!", "Connection Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String sql = "SELECT * FROM tbl_products WHERE status = 'Available' AND quantity > 0 ORDER BY product_name";
            pstmt = conn.prepareStatement(sql);
            rs = pstmt.executeQuery();

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("product_id"),
                    rs.getString("product_name"),
                    rs.getString("description"),
                    String.format("%.2f", rs.getDouble("price")),
                    rs.getInt("quantity"),
                    rs.getString("category"),
                    rs.getString("status")
                };
                model.addRow(row);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading products: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        searchbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        viewordersbtn = new javax.swing.JButton();
        buybtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactiontbl = new javax.swing.JTable();
        refreshbtn = new javax.swing.JButton();
        search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 90, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CREATE TRANSACTION");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, 30));

        viewordersbtn.setText("View my Orders");
        viewordersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewordersbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(viewordersbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 130, 30));

        buybtn.setText("Select / Buy");
        buybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buybtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(buybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 120, 30));

        transactiontbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(transactiontbl);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 790, -1));

        refreshbtn.setText("Refresh");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 90, 30));

        search.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        search.setOpaque(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jDesktopPane1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        String keyword = search.getText().trim();
        if (keyword.isEmpty()) {
            loadProductsTable();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) transactiontbl.getModel();
        model.setRowCount(0);

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

         try {
            conf dbConfig = new conf();
            conn = dbConfig.connectDB();
            String sql = "SELECT t.transaction_id, t.customer_name, t.total_amount, t.transaction_date, " +
    "t.payment_method, u.username as cashier " +
    "FROM tbl_transactions t JOIN tbl_users u ON t.u_id = u.u_id " +
    "WHERE t.customer_name LIKE ? OR CAST(t.transaction_id AS TEXT) LIKE ? " +  // ← ADD WHERE
    "ORDER BY t.transaction_date DESC";
pstmt = conn.prepareStatement(sql);
String pattern = "%" + keyword + "%";
pstmt.setString(1, pattern);
pstmt.setString(2, pattern);
rs = pstmt.executeQuery();

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("transaction_id"),
                    rs.getString("customer_name"),
                    String.format("%.2f", rs.getDouble("total_amount")),
                    rs.getString("transaction_date"),
                    rs.getString("payment_method"),
                    rs.getString("cashier")
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Search error: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     user.userdashboard dashboard = new user.userdashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void viewordersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewordersbtnActionPerformed
        user.ViewTransac vt = new user.ViewTransac();
        vt.setVisible(true);
        this.dispose();
    
    }

    private boolean updateTransaction(int transId, String customerName, String paymentMethod) {
        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            conf dbConfig = new conf();
            conn = dbConfig.connectDB();
            String sql = "UPDATE tbl_transactions SET customer_name = ?, payment_method = ? WHERE transaction_id = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, customerName);
            pstmt.setString(2, paymentMethod);
            pstmt.setInt(3, transId);
            return pstmt.executeUpdate() > 0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return false;
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_viewordersbtnActionPerformed

    private void buybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buybtnActionPerformed
     int selectedRow = transactiontbl.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product to buy");
            return;
        }

        int productId = (int) transactiontbl.getValueAt(selectedRow, 0);
        String productName = (String) transactiontbl.getValueAt(selectedRow, 1);
        double price = Double.parseDouble(transactiontbl.getValueAt(selectedRow, 3).toString());
        int availableStock = (int) transactiontbl.getValueAt(selectedRow, 4);

        String customerName = JOptionPane.showInputDialog(this, "Enter Customer Name:", "New Transaction", JOptionPane.QUESTION_MESSAGE);
        if (customerName == null || customerName.trim().isEmpty()) return;

        String qtyStr = JOptionPane.showInputDialog(this,
            "Product: " + productName + "\nPrice: " + String.format("%.2f", price) + 
            "\nAvailable: " + availableStock + "\n\nEnter Quantity:",
            "Enter Quantity", JOptionPane.QUESTION_MESSAGE);
        if (qtyStr == null) return;

        int quantity;
        try {
            quantity = Integer.parseInt(qtyStr.trim());
            if (quantity <= 0) throw new NumberFormatException();
            if (quantity > availableStock) {
                JOptionPane.showMessageDialog(this, "Not enough stock! Available: " + availableStock, "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] paymentOptions = {"Cash", "Credit Card", "Debit Card", "Online Payment"};
        String paymentMethod = (String) JOptionPane.showInputDialog(this,
            "Select Payment Method:", "Payment Method",
            JOptionPane.QUESTION_MESSAGE, null, paymentOptions, paymentOptions[0]);
        if (paymentMethod == null) return;

        double totalAmount = quantity * price;

        int confirm = JOptionPane.showConfirmDialog(this,
            "Transaction Summary:\n\n" +
            "Customer: " + customerName + "\n" +
            "Product: " + productName + "\n" +
            "Quantity: " + quantity + "\n" +
            "Total: " + String.format("%.2f", totalAmount) + "\n" +
            "Payment: " + paymentMethod + "\n\n" +
            "Confirm transaction?",
            "Confirm Transaction", JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) return;

        if (saveTransaction(customerName, productId, productName, quantity, price, totalAmount, paymentMethod)) {
            JOptionPane.showMessageDialog(this, "Transaction completed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadProductsTable();
            showReceipt(customerName, productName, quantity, price, totalAmount, paymentMethod);
        } else {
            JOptionPane.showMessageDialog(this, "Transaction failed!", "Error", JOptionPane.ERROR_MESSAGE);{
        }
        }
        }
        private boolean saveTransaction(String customerName, int productId, String productName, int quantity,
        double price, double totalAmount, String paymentMethod) {
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conf dbConfig = new conf();
            conn = dbConfig.connectDB();
            conn.setAutoCommit(false);

            String sqlTrans = "INSERT INTO tbl_transactions (u_id, customer_name, total_amount, payment_method) VALUES (?, ?, ?, ?)";
            pstmt = conn.prepareStatement(sqlTrans, Statement.RETURN_GENERATED_KEYS);
            pstmt.setInt(1, Session.getInstance().getU_id());
            pstmt.setString(2, customerName);
            pstmt.setDouble(3, totalAmount);
            pstmt.setString(4, paymentMethod);
            pstmt.executeUpdate();

            rs = pstmt.getGeneratedKeys();
            int transId = 0;
            if (rs.next()) transId = rs.getInt(1);

            String sqlItem = "INSERT INTO tbl_transaction_items (transaction_id, product_id, book_title, quantity, price, subtotal) VALUES (?, ?, ?, ?, ?, ?)";
            pstmt = conn.prepareStatement(sqlItem);
            pstmt.setInt(1, transId);
            pstmt.setInt(2, productId);
            pstmt.setString(3, productName);
            pstmt.setInt(4, quantity);
            pstmt.setDouble(5, price);
            pstmt.setDouble(6, totalAmount);
            pstmt.executeUpdate();

            String sqlUpdateStock = "UPDATE tbl_products SET quantity = quantity - ? WHERE product_id = ?";
            pstmt = conn.prepareStatement(sqlUpdateStock);
            pstmt.setInt(1, quantity);
            pstmt.setInt(2, productId);
            pstmt.executeUpdate();

            conn.commit();
            return true;
        } catch (Exception e) {
            try { if (conn != null) conn.rollback(); } catch (Exception ex) { ex.printStackTrace(); }
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return false;
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) { conn.setAutoCommit(true); conn.close(); }
            } catch (Exception e) { e.printStackTrace(); }
        }
    }

    private void showReceipt(String customerName, String bookTitle, int quantity,
            double price, double totalAmount, String paymentMethod) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String date = sdf.format(new Date());

        StringBuilder receipt = new StringBuilder();
        receipt.append("========================================\n");
        receipt.append("        NOVEL'S BOOK SHOP\n");
        receipt.append("           SALES RECEIPT\n");
        receipt.append("========================================\n");
        receipt.append("Date: ").append(date).append("\n");
        receipt.append("Customer: ").append(customerName).append("\n");
        receipt.append("Cashier: ").append(Session.getInstance().getUsername()).append("\n");
        receipt.append("----------------------------------------\n");
        receipt.append(String.format("%-20s %3s %10s\n", "Item", "Qty", "Amount"));
        receipt.append("----------------------------------------\n");
        String shortTitle = bookTitle.length() > 20 ? bookTitle.substring(0, 17) + "..." : bookTitle;
        receipt.append(String.format("%-20s %3d %10.2f\n", shortTitle, quantity, totalAmount));
        receipt.append("----------------------------------------\n");
        receipt.append(String.format("%-24s %10.2f\n", "TOTAL:", totalAmount));
        receipt.append(String.format("%-24s %10s\n", "Payment:", paymentMethod));
        receipt.append("========================================\n");
        receipt.append("     Thank you for your purchase!\n");
        receipt.append("========================================\n");

        javax.swing.JTextArea textArea = new javax.swing.JTextArea(receipt.toString());
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        textArea.setEditable(false);
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(400, 400));
        JOptionPane.showMessageDialog(this, scrollPane, "Receipt", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_buybtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
          loadProductsTable();
        JOptionPane.showMessageDialog(this, "Product list refreshed!", "Refresh", JOptionPane.INFORMATION_MESSAGE);
    


    }//GEN-LAST:event_refreshbtnActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
         String keyword = search.getText().trim();
        if (keyword.isEmpty()) {
            loadProductsTable();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) transactiontbl.getModel();
        model.setRowCount(0);

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conf dbConfig = new conf();
            conn = dbConfig.connectDB();
            String sql = "SELECT * FROM tbl_products WHERE product_name LIKE ? OR category LIKE ? OR description LIKE ?";
            pstmt = conn.prepareStatement(sql);
            String pattern = "%" + keyword + "%";
            pstmt.setString(1, pattern);
            pstmt.setString(2, pattern);
            pstmt.setString(3, pattern);
            
            rs = pstmt.executeQuery();

            while (rs.next()) {
                Object[] row = {
                     rs.getInt("product_id"),
                    rs.getString("product_name"),
                    rs.getString("description"),
                    String.format("%.2f", rs.getDouble("price")),
                    rs.getInt("quantity"),
                    rs.getString("category"),
                    rs.getString("status")
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Search error: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTransac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buybtn;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTable transactiontbl;
    private javax.swing.JButton viewordersbtn;
    // End of variables declaration//GEN-END:variables
}
