/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.Session;
import config.conf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import laroa.UProfile;
import laroa.login;

/**
 *
 * @author USER23
 */
public class usertbl extends javax.swing.JFrame {

    /**
     * Creates new form usertbl
     */
    public usertbl() {
        if (Session.getInstance().getU_id() == 0) {
        JOptionPane.showMessageDialog(null, "Please login first!");
        laroa.login log = new laroa.login();
        log.setVisible(true);
        this.dispose();
        return;
    }
    
        initComponents();
        loadUsersTable(); // Load data when form opens
    }
    private void loadUsersTable() {
     DefaultTableModel model = (DefaultTableModel) userstbl.getModel();
    model.setRowCount(0); // Clear existing data
    
    // Set column headers
    model.setColumnIdentifiers(new String[]{"ID", "Username", "Email", "Type", "Status"});
    
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    
    try {
        // FIXED: Create instance of conf
        conf dbConfig = new conf();
        conn = dbConfig.connectDB();
        
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Database connection failed!");
            return;
        }
        
        String sql = "SELECT u_id, username, email, type, status FROM tbl_users";
        pstmt = conn.prepareStatement(sql);
        rs = pstmt.executeQuery();
        
        while (rs.next()) {
            Object[] row = {
                rs.getInt("u_id"),
                rs.getString("username"),
                rs.getString("email"),
                rs.getString("type"),
                rs.getString("status")
            };
            model.addRow(row);
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading users: " + e.getMessage());
        e.printStackTrace();
    } finally {
        // Close resources
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        searchbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        userbtn = new javax.swing.JButton();
        editbtd = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userstbl = new javax.swing.JTable();
        deletebtn = new javax.swing.JButton();
        search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 90, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DASHBOARD");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jButton8.setText("Home");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 90, 30));

        userbtn.setText("User");
        userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(userbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 90, 30));

        editbtd.setText("Edit");
        editbtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtdActionPerformed(evt);
            }
        });
        jDesktopPane1.add(editbtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 90, 30));

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, 30));

        userstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userstbl);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 790, -1));

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 90, 30));

        search.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        search.setOpaque(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jDesktopPane1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
    
    }//GEN-LAST:event_searchbtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void userbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnActionPerformed
 user.userdashboard userDash = new user.userdashboard();
        userDash.setVisible(true);
        this.dispose();
                      // TODO add your handling code here:
    }//GEN-LAST:event_userbtnActionPerformed

    private void editbtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtdActionPerformed
    int selectedRow = userstbl.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user to edit");
        return;
    }
    
    // Get the user ID from the selected row
    int userId = (int) userstbl.getValueAt(selectedRow, 0);
    
    // Open the edit form and pass the user ID
    laroa.edit editForm = new laroa.edit(userId);
    editForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_editbtdActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // Step 1: Get Username
    String username = JOptionPane.showInputDialog(this, "Enter Username:", "Add User - Step 1/4", JOptionPane.QUESTION_MESSAGE);
    
    // Check if user cancelled
    if (username == null) {
        return; // User clicked Cancel
    }
    
    // Validate username
    if (username.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Check if username already exists
    if (isUsernameExists(username.trim())) {
        JOptionPane.showMessageDialog(this, "Username already exists!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Step 2: Get Email
    String email = JOptionPane.showInputDialog(this, "Enter Email:", "Add User - Step 2/4", JOptionPane.QUESTION_MESSAGE);
    
    if (email == null) {
        return; // User clicked Cancel
    }
    
    // Validate email
    if (email.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Email cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Check if email already exists
    if (isEmailExists(email.trim())) {
        JOptionPane.showMessageDialog(this, "Email already exists!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Step 3: Get Password
    String password = JOptionPane.showInputDialog(this, "Enter Password:", "Add User - Step 3/4", JOptionPane.QUESTION_MESSAGE);
    
    if (password == null) {
        return; // User clicked Cancel
    }
    
    // Validate password
    if (password.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Step 4: Confirm and Add
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Add user '" + username + "' to database?", 
        "Add User - Step 4/4", 
        JOptionPane.OK_CANCEL_OPTION);
    
    if (confirm != JOptionPane.OK_OPTION) {
        return; // User cancelled
    }
    
    // Add user to database
    if (addUserToDatabase(username.trim(), email.trim(), password)) {
        JOptionPane.showMessageDialog(this, "Added completely!", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadUsersTable(); // Refresh the table
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add user!", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// Helper method: Check if username exists
private boolean isUsernameExists(String username) {
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    
    try {
        conf dbConfig = new conf();
        conn = dbConfig.connectDB();
        String sql = "SELECT u_id FROM tbl_users WHERE username = ?";
        pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, username);
        rs = pstmt.executeQuery();
        return rs.next(); // Returns true if found
    } catch (Exception e) {
        e.printStackTrace();
        return false;
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

// Helper method: Check if email exists
private boolean isEmailExists(String email) {
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    
    try {
        conf dbConfig = new conf();
        conn = dbConfig.connectDB();
        String sql = "SELECT u_id FROM tbl_users WHERE email = ?";
        pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, email);
        rs = pstmt.executeQuery();
        return rs.next(); // Returns true if found
    } catch (Exception e) {
        e.printStackTrace();
        return false;
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

// Helper method: Add user to database
private boolean addUserToDatabase(String username, String email, String password) {
    Connection conn = null;
    PreparedStatement pstmt = null;
    
    try {
        conf dbConfig = new conf();
        conn = dbConfig.connectDB();
        
        String sql = "INSERT INTO tbl_users (username, email, password, type, status) VALUES (?, ?, ?, 'user', 'Active')";
        pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, username);
        pstmt.setString(2, email);
        pstmt.setString(3, password);
        
        int rowsAffected = pstmt.executeUpdate();
        return rowsAffected > 0;
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        return false;
    } finally {
        try {
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }        }

        private void jButtonProfileActionPerformed(java.awt.event.ActionEvent evt) {
            
    }//GEN-LAST:event_addbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
    int selectedRow = userstbl.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to delete");
            return;
        }
        
        int userId = (int) userstbl.getValueAt(selectedRow, 0);
        String username = (String) userstbl.getValueAt(selectedRow, 1);
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Delete user: " + username + "?", 
            "Confirm Delete", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            deleteUser(userId);
            loadUsersTable();
        }
    }

    private void deleteUser(int userId) {
       Connection conn = null;
    PreparedStatement pstmt = null;
    
    try {
        conf dbConfig = new conf();
        conn = dbConfig.connectDB();
        
        String sql = "DELETE FROM tbl_users WHERE u_id = ?";
        pstmt = conn.prepareStatement(sql);
        pstmt.setInt(1, userId);
        
        int rowsAffected = pstmt.executeUpdate();
        
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "User deleted successfully");
        } else {
            JOptionPane.showMessageDialog(this, "User not found or already deleted");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error deleting user: " + e.getMessage());
        e.printStackTrace();
    } finally {
        try {
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
 	
    }//GEN-LAST:event_deletebtnActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
    String keyword = search.getText().trim();
    
    if (keyword.isEmpty()) {
        loadUsersTable(); // Show all if empty
        return;
    }
    
    DefaultTableModel model = (DefaultTableModel) userstbl.getModel();
    model.setRowCount(0);
    
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    
    try {
        conf dbConfig = new conf();
        conn = dbConfig.connectDB();
        
        // Search in username, email, or type
        String sql = "SELECT u_id, username, email, type, status FROM tbl_users " +
                     "WHERE username LIKE ? OR email LIKE ? OR type LIKE ?";
        pstmt = conn.prepareStatement(sql);
        String searchPattern = "%" + keyword + "%";
        pstmt.setString(1, searchPattern);
        pstmt.setString(2, searchPattern);
        pstmt.setString(3, searchPattern);
        
        rs = pstmt.executeQuery();
        
        boolean found = false;
        while (rs.next()) {
            found = true;
            Object[] row = {
                rs.getInt("u_id"),
                rs.getString("username"),
                rs.getString("email"),
                rs.getString("type"),
                rs.getString("status")
            };
            model.addRow(row);
        }
        
        if (!found) {
            JOptionPane.showMessageDialog(this, "No results found for: '" + keyword + "'");
            loadUsersTable(); // Reload all
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Search error: " + e.getMessage());
        e.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usertbl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usertbl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usertbl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usertbl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usertbl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton editbtd;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton userbtn;
    private javax.swing.JTable userstbl;
    // End of variables declaration//GEN-END:variables
}
