/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import config.Session;
import config.conf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pc1
 */
public class ViewTransac extends javax.swing.JFrame {

    /**
     * Creates new form ViewTransac
     */
    public ViewTransac() {
     if (Session.getInstance().getU_id() == 0) {
            JOptionPane.showMessageDialog(null, "Please login first!");
            laroa.login log = new laroa.login();
            log.setVisible(true);
            this.dispose();
            return;
        }
        initComponents();
        loadMyTransactions(); // <-- Just call the method, don't define it here!
    }
     private void loadMyTransactions() {
        DefaultTableModel model = (DefaultTableModel) transactiontbl.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{"Trans ID", "Customer", "Total Amount", "Date", "Payment Method", "Cashier"});

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conf dbConfig = new conf();
            conn = dbConfig.connectDB();
            
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Database connection failed!", "Connection Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Only show current user's transactions
            String sql = "SELECT t.transaction_id, t.customer_name, t.total_amount, t.transaction_date, " +
                "t.payment_method, u.username as cashier " +
                "FROM tbl_transactions t JOIN tbl_users u ON t.u_id = u.u_id " +
                "WHERE t.u_id = ? " +
                "ORDER BY t.transaction_date DESC";
                
            pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, Session.getInstance().getU_id());
            rs = pstmt.executeQuery();

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("transaction_id"),
                    rs.getString("customer_name"),
                    String.format("%.2f", rs.getDouble("total_amount")),
                    rs.getString("transaction_date"),
                    rs.getString("payment_method"),
                    rs.getString("cashier")
                };
                model.addRow(row);
            }
            
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No transactions found.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading transactions: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } // Load transactions on startup
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        searchbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        VieWDetailsbtn = new javax.swing.JButton();
        buybtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactiontbl = new javax.swing.JTable();
        refreshbtn = new javax.swing.JButton();
        search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 90, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("My Transactions");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 200, -1));

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, 30));

        VieWDetailsbtn.setText("View Details");
        VieWDetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VieWDetailsbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(VieWDetailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 110, 30));

        buybtn.setText("Cancel/Delete");
        buybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buybtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(buybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 110, 30));

        transactiontbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(transactiontbl);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 790, -1));

        refreshbtn.setText("Refresh");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 90, 30));

        search.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        search.setOpaque(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jDesktopPane1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        String keyword = search.getText().trim();
        if (keyword.isEmpty()) {
            loadMyTransactions();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) transactiontbl.getModel();
        model.setRowCount(0);

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conf dbConfig = new conf();
            conn = dbConfig.connectDB();
            
            // Search only current user's transactions
            String sql = "SELECT t.transaction_id, t.customer_name, t.total_amount, t.transaction_date, " +
                "t.payment_method, u.username as cashier " +
                "FROM tbl_transactions t JOIN tbl_users u ON t.u_id = u.u_id " +
                "WHERE t.u_id = ? AND (t.customer_name LIKE ? OR CAST(t.transaction_id AS TEXT) LIKE ?) " +
                "ORDER BY t.transaction_date DESC";
                
            pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, Session.getInstance().getU_id());
            String pattern = "%" + keyword + "%";
            pstmt.setString(2, pattern);
            pstmt.setString(3, pattern);
            rs = pstmt.executeQuery();

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("transaction_id"),
                    rs.getString("customer_name"),
                    String.format("%.2f", rs.getDouble("total_amount")),
                    rs.getString("transaction_date"),
                    rs.getString("payment_method"),
                    rs.getString("cashier")
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Search error: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      user.CreateTransac ct = new user.CreateTransac();
        ct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void VieWDetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VieWDetailsbtnActionPerformed
         int selectedRow = transactiontbl.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a transaction to view details");
            return;
        }

        int transId = (int) transactiontbl.getValueAt(selectedRow, 0);
        showTransactionDetails(transId);
    }

    private void showTransactionDetails(int transId) {
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        StringBuilder details = new StringBuilder();

        try {
            conf dbConfig = new conf();
            conn = dbConfig.connectDB();
            
            // Get transaction info
            String sqlTrans = "SELECT * FROM tbl_transactions WHERE transaction_id = ?";
            pstmt = conn.prepareStatement(sqlTrans);
            pstmt.setInt(1, transId);
            rs = pstmt.executeQuery();
            
            if (rs.next()) {
                details.append("Transaction ID: ").append(transId).append("\n");
                details.append("Customer: ").append(rs.getString("customer_name")).append("\n");
                details.append("Date: ").append(rs.getString("transaction_date")).append("\n");
                details.append("Payment: ").append(rs.getString("payment_method")).append("\n");
                details.append("Total: ").append(String.format("%.2f", rs.getDouble("total_amount"))).append("\n\n");
            }
            
            // Get items
            String sqlItems = "SELECT * FROM tbl_transaction_items WHERE transaction_id = ?";
            pstmt = conn.prepareStatement(sqlItems);
            pstmt.setInt(1, transId);
            rs = pstmt.executeQuery();
            
            details.append("Items:\n");
            details.append("----------------------------------------\n");
            while (rs.next()) {
                details.append("Product: ").append(rs.getString("book_title")).append("\n");
                details.append("Qty: ").append(rs.getInt("quantity")).append(" x ");
                details.append(String.format("%.2f", rs.getDouble("price"))).append(" = ");
                details.append(String.format("%.2f", rs.getDouble("subtotal"))).append("\n\n");
            }
            
            JOptionPane.showMessageDialog(this, details.toString(), "Transaction Details", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_VieWDetailsbtnActionPerformed

    private void buybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buybtnActionPerformed
        int selectedRow = transactiontbl.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a transaction to cancel");
            return;
        }

        int transId = (int) transactiontbl.getValueAt(selectedRow, 0);
        String customer = (String) transactiontbl.getValueAt(selectedRow, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Cancel transaction for " + customer + "?\n(Transaction ID: " + transId + ")\n\nThis will restore product stock.",
            "Confirm Cancel", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (cancelTransaction(transId)) {
                JOptionPane.showMessageDialog(this, "Transaction cancelled successfully");
                loadMyTransactions(); // Refresh
            } else {
                JOptionPane.showMessageDialog(this, "Failed to cancel transaction", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private boolean cancelTransaction(int transId) {
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conf dbConfig = new conf();
            conn = dbConfig.connectDB();
            conn.setAutoCommit(false);

            // Restore stock first
            String sqlGetItems = "SELECT product_id, quantity FROM tbl_transaction_items WHERE transaction_id = ?";
            pstmt = conn.prepareStatement(sqlGetItems);
            pstmt.setInt(1, transId);
            rs = pstmt.executeQuery();
            
            while (rs.next()) {
                int productId = rs.getInt("product_id");
                int qty = rs.getInt("quantity");
                
                String sqlRestore = "UPDATE tbl_products SET quantity = quantity + ? WHERE product_id = ?";
                pstmt = conn.prepareStatement(sqlRestore);
                pstmt.setInt(1, qty);
                pstmt.setInt(2, productId);
                pstmt.executeUpdate();
            }

            // Delete items
            String sqlDeleteItems = "DELETE FROM tbl_transaction_items WHERE transaction_id = ?";
            pstmt = conn.prepareStatement(sqlDeleteItems);
            pstmt.setInt(1, transId);
            pstmt.executeUpdate();

            // Delete transaction
            String sqlDeleteTrans = "DELETE FROM tbl_transactions WHERE transaction_id = ?";
            pstmt = conn.prepareStatement(sqlDeleteTrans);
            pstmt.setInt(1, transId);
            int rows = pstmt.executeUpdate();

            conn.commit();
            return rows > 0;
            
        } catch (Exception e) {
            try { if (conn != null) conn.rollback(); } catch (Exception ex) { ex.printStackTrace(); }
            e.printStackTrace();
            return false;
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) { conn.setAutoCommit(true); conn.close(); }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_buybtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        loadMyTransactions();
        JOptionPane.showMessageDialog(this, "Transaction list refreshed!", "Refresh", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_refreshbtnActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
         searchbtnActionPerformed(evt);
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTransac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VieWDetailsbtn;
    private javax.swing.JButton buybtn;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTable transactiontbl;
    // End of variables declaration//GEN-END:variables
}
